builds:
  - binary: codeperf
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=mod

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  prerelease: auto

universal_binaries:
  - replace: false

brews:
  -
    name: codeperf
    homepage: "https://codeperf.io"
    description: "Export, persist and compare profiling data using https://codeperf.io."

    tap:
      owner: codeperfio
      name: homebrew-codeperf

    commit_author:
      name: codeperf.io
      email: hello@codeperf.io

checksum:
  name_template: 'checksums.txt'
